# Generated by Django 5.2.14 on 2026-06-10 22:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='vulnerabilidade_alvo',
            field=models.DecimalField(decimal_places=1, default=3.5, help_text='Escala 0–10. 0 = cru, 10 = impessoal.', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
