# Generated by Django 5.2.14 on 2026-05-25 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BacklogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_externo', models.CharField(help_text='Identificador do backlog, ex: "1.1.1"', max_length=16)),
                ('titulo', models.CharField(max_length=255)),
                ('secao', models.CharField(choices=[('decisoes', 'Decisões'), ('saude', 'Saúde'), ('familia', 'Família'), ('dedicacao_exclusiva', 'Dedicação exclusiva'), ('identidade_digital', 'Identidade digital'), ('captura', 'Captura'), ('producao', 'Produção'), ('ambiente', 'Ambiente'), ('dia_zero', 'Dia zero'), ('conteudo', 'Conteúdo'), ('metricas', 'Métricas'), ('suporte', 'Suporte'), ('filosofia', 'Filosofia')], max_length=32)),
                ('prioridade', models.CharField(choices=[('alta', 'Alta'), ('media', 'Média'), ('baixa', 'Baixa')], default='media', max_length=8)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em andamento'), ('aguardando', 'Aguardando'), ('bloqueado', 'Bloqueado'), ('concluido', 'Concluído'), ('adiado', 'Adiado'), ('descartado', 'Descartado')], default='pendente', max_length=16)),
                ('responsavel', models.CharField(choices=[('eu', 'Eu'), ('eu+esposa', 'Eu + esposa'), ('medico', 'Médico'), ('rh', 'RH'), ('terapeuta', 'Terapeuta')], default='eu', max_length=16)),
                ('custo_estimado_brl', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('custo_real_brl', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('prazo_alvo', models.DateField(blank=True, null=True)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_conclusao', models.DateField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('contexto', models.TextField(blank=True)),
                ('criterio_pronto', models.JSONField(blank=True, default=list, help_text='lista de {texto, done}')),
                ('decisao', models.TextField(blank=True)),
                ('notas', models.TextField(blank=True)),
                ('historico', models.JSONField(blank=True, default=list, help_text='lista de {ts, evento}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blocked_by', models.ManyToManyField(blank=True, related_name='blocks', to='backlog.backlogitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backlog_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id_externo'],
                'unique_together': {('user', 'id_externo')},
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255)),
                ('categoria', models.CharField(choices=[('medicamento', 'Medicamento'), ('equipamento', 'Equipamento'), ('livro', 'Livro'), ('substituicao', 'Substituição'), ('software', 'Software'), ('outro', 'Outro')], max_length=16)),
                ('fornecedor', models.CharField(blank=True, max_length=128)),
                ('preco_brl', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pedido', 'Pedido'), ('recebido', 'Recebido'), ('cancelado', 'Cancelado')], default='pendente', max_length=12)),
                ('data_pedido', models.DateField(blank=True, null=True)),
                ('data_recebimento', models.DateField(blank=True, null=True)),
                ('justificativa', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('itens_atendidos', models.ManyToManyField(blank=True, related_name='compras', to='backlog.backlogitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profissional', models.CharField(blank=True, max_length=128)),
                ('especialidade', models.CharField(choices=[('psiquiatra', 'Psiquiatra'), ('clinico', 'Clínico'), ('terapia', 'Terapia'), ('clinica_canabis', 'Clínica canabis'), ('outro', 'Outro')], max_length=24)),
                ('data', models.DateField()),
                ('modalidade', models.CharField(choices=[('presencial', 'Presencial'), ('tele', 'Teleconsulta'), ('hibrido', 'Híbrido')], default='tele', max_length=12)),
                ('custo_brl', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('proxima_data', models.DateField(blank=True, null=True)),
                ('pauta', models.TextField(blank=True)),
                ('anamnese', models.TextField(blank=True)),
                ('conduta', models.TextField(blank=True)),
                ('decisoes', models.TextField(blank=True)),
                ('proximos_passos', models.JSONField(blank=True, default=list, help_text='lista de {texto, done}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('itens_impactados', models.ManyToManyField(blank=True, related_name='consultas', to='backlog.backlogitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_externo', models.CharField(help_text='ex: "D-001"', max_length=16)),
                ('titulo', models.CharField(max_length=255)),
                ('status', models.CharField(default='aceita', max_length=24)),
                ('data', models.DateField()),
                ('contexto', models.TextField(blank=True)),
                ('opcoes', models.JSONField(blank=True, default=list, help_text='opções consideradas')),
                ('decisao', models.TextField(blank=True)),
                ('consequencias_positivas', models.TextField(blank=True)),
                ('consequencias_negativas', models.TextField(blank=True)),
                ('reversibilidade', models.CharField(blank=True, choices=[('alta', 'Alta'), ('media', 'Média'), ('baixa', 'Baixa')], max_length=8)),
                ('quando_revisitar', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relacionada_a', models.ManyToManyField(blank=True, related_name='decisions', to='backlog.backlogitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data'],
                'unique_together': {('user', 'id_externo')},
            },
        ),
    ]
