# Generated by Django 5.2.14 on 2026-05-25 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('baseline', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Slip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('substancia', models.CharField(choices=[('alcool', 'Álcool'), ('tabaco', 'Tabaco')], max_length=8)),
                ('quantidade', models.CharField(blank=True, help_text='ex: 2 cervejas, 3 cigarros', max_length=64)),
                ('contexto', models.TextField(blank=True)),
                ('gatilho_texto', models.CharField(blank=True, max_length=255)),
                ('aprendizado', models.TextField(blank=True)),
                ('reset_streak_alcool', models.BooleanField(default=False)),
                ('reset_streak_tabaco', models.BooleanField(default=False)),
                ('cooldown_publicacao_ate', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trigger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseline.trigger')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CravingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('substancia', models.CharField(choices=[('alcool', 'Álcool'), ('tabaco', 'Tabaco'), ('ambos', 'Ambos')], max_length=8)),
                ('intensidade_pico', models.PositiveSmallIntegerField(help_text='0–10')),
                ('duracao_min', models.PositiveSmallIntegerField(default=0)),
                ('intensidade_final', models.PositiveSmallIntegerField(default=0, help_text='0–10')),
                ('tempo_para_baixar_3', models.PositiveSmallIntegerField(blank=True, help_text='min até ≤3', null=True)),
                ('gatilho_texto', models.CharField(max_length=255)),
                ('halt', models.JSONField(blank=True, default=dict)),
                ('pensamento_automatico', models.TextField(blank=True)),
                ('evidencia_favor', models.TextField(blank=True)),
                ('evidencia_contra', models.TextField(blank=True)),
                ('pensamento_balanceado', models.TextField(blank=True)),
                ('aprendizado', models.CharField(blank=True, max_length=255)),
                ('publicable', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('if_then_gerado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evento_origem', to='baseline.ifthenplan')),
                ('substituicao_usada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseline.substitution')),
                ('trigger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseline.trigger')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cravings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='log_craving_user_id_5aa4e5_idx')],
            },
        ),
        migrations.CreateModel(
            name='DailyEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('humor', models.PositiveSmallIntegerField(help_text='1–5')),
                ('energia', models.PositiveSmallIntegerField(help_text='1–5')),
                ('sono_h', models.DecimalField(decimal_places=1, max_digits=3)),
                ('sono_q', models.PositiveSmallIntegerField(help_text='1–5')),
                ('craving_pico', models.PositiveSmallIntegerField(default=0, help_text='0–10')),
                ('halt', models.JSONField(blank=True, default=dict, help_text='ex: {"H": false, "A": true, ...}')),
                ('linha_1', models.CharField(blank=True, max_length=255)),
                ('linha_2', models.CharField(blank=True, max_length=255)),
                ('linha_3', models.CharField(blank=True, max_length=255)),
                ('algo_do_corpo', models.CharField(blank=True, max_length=255)),
                ('coisa_boa', models.CharField(blank=True, max_length=255)),
                ('coisa_dificil', models.CharField(blank=True, max_length=255)),
                ('halt_check_feito', models.BooleanField(default=False)),
                ('cravings_logados', models.BooleanField(default=False)),
                ('publicable', models.BooleanField(default=False)),
                ('publicable_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('substituicoes', models.ManyToManyField(blank=True, to='baseline.substitution')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data'],
                'indexes': [models.Index(fields=['user', '-data'], name='log_dailyen_user_id_df039e_idx')],
                'unique_together': {('user', 'data')},
            },
        ),
    ]
