# Generated by Django 5.2.14 on 2026-05-25 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseline', '0002_remove_trigger_halt_mais_comum_estadointerno_and_more'),
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cravingevent',
            name='halt',
        ),
        migrations.RemoveField(
            model_name='dailyentry',
            name='halt',
        ),
        migrations.RemoveField(
            model_name='dailyentry',
            name='halt_check_feito',
        ),
        migrations.AddField(
            model_name='cravingevent',
            name='estados',
            field=models.ManyToManyField(blank=True, related_name='cravings', to='baseline.estadointerno'),
        ),
        migrations.AddField(
            model_name='dailyentry',
            name='estado_checado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailyentry',
            name='estados',
            field=models.ManyToManyField(blank=True, related_name='daily_entries', to='baseline.estadointerno'),
        ),
    ]
