# Generated by Django 5.2.14 on 2026-06-09 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseline', '0003_baselineprofile_baseline_circ_abdominal'),
        ('log', '0002_remove_cravingevent_halt_remove_dailyentry_halt_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pulso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('humor', models.PositiveSmallIntegerField(help_text='1–5')),
                ('energia', models.PositiveSmallIntegerField(help_text='1–5')),
                ('nota', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('estados', models.ManyToManyField(blank=True, related_name='pulsos', to='baseline.estadointerno')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pulsos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='log_pulso_user_id_ec6ee8_idx')],
            },
        ),
    ]
