# Generated by Django 5.2.14 on 2026-06-10 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0003_pulso'),
    ]

    operations = [
        migrations.AddField(
            model_name='pulso',
            name='craving',
            field=models.PositiveSmallIntegerField(default=0, help_text='0–10'),
        ),
    ]
