# Generated by Django 5.2.14 on 2026-06-10 22:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0004_pulso_craving'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cravingevent',
            name='intensidade_final',
            field=models.PositiveSmallIntegerField(default=0, help_text='0–10', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='cravingevent',
            name='intensidade_pico',
            field=models.PositiveSmallIntegerField(help_text='0–10', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='dailyentry',
            name='craving_pico',
            field=models.PositiveSmallIntegerField(default=0, help_text='0–10', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='dailyentry',
            name='energia',
            field=models.PositiveSmallIntegerField(help_text='1–5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='dailyentry',
            name='humor',
            field=models.PositiveSmallIntegerField(help_text='1–5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='dailyentry',
            name='sono_q',
            field=models.PositiveSmallIntegerField(help_text='1–5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='pulso',
            name='craving',
            field=models.PositiveSmallIntegerField(default=0, help_text='0–10', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='pulso',
            name='energia',
            field=models.PositiveSmallIntegerField(help_text='1–5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='pulso',
            name='humor',
            field=models.PositiveSmallIntegerField(help_text='1–5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
