# Generated by Django 5.2.14 on 2026-06-20 23:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0005_alter_cravingevent_intensidade_final_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyentry',
            name='energia',
            field=models.PositiveSmallIntegerField(help_text='0–10', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='dailyentry',
            name='humor',
            field=models.PositiveSmallIntegerField(help_text='0–10', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='dailyentry',
            name='sono_q',
            field=models.PositiveSmallIntegerField(help_text='0–10', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='pulso',
            name='energia',
            field=models.PositiveSmallIntegerField(help_text='0–10', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='pulso',
            name='humor',
            field=models.PositiveSmallIntegerField(help_text='0–10', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
