# Generated by Django 5.2.14 on 2026-07-12 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0008_gatilho_taxonomia_dados'),
        ('baseline', '0005_ifthen_gatilho_dados'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cravingevent',
            name='estados_m2m',
        ),
        migrations.RemoveField(
            model_name='cravingevent',
            name='gatilho_texto',
        ),
        migrations.RemoveField(
            model_name='cravingevent',
            name='trigger',
        ),
        migrations.RemoveField(
            model_name='dailyentry',
            name='estados_m2m',
        ),
        migrations.RemoveField(
            model_name='pulso',
            name='estados_m2m',
        ),
        migrations.RemoveField(
            model_name='slip',
            name='gatilho_texto',
        ),
        migrations.RemoveField(
            model_name='slip',
            name='trigger',
        ),
    ]
