# Generated by Django 5.2.14 on 2026-07-13 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0009_gatilho_taxonomia_remove'),
    ]

    operations = [
        migrations.AddField(
            model_name='cravingevent',
            name='substituicao',
            field=models.CharField(blank=True, choices=[('oral', 'Oral — chá, água, goma, comer algo'), ('movimento', 'Movimento — andar, correr, alongar, qualquer coisa com o corpo'), ('social', 'Social — ligar, mandar mensagem, ficar perto de alguém'), ('cognitivo', 'Cognitivo — escrever, ler, respirar, esperar a onda passar'), ('ambiental', 'Ambiental — mudar de ambiente, sair da situação')], max_length=16),
        ),
        migrations.AddField(
            model_name='cravingevent',
            name='substituicao_detalhes',
            field=models.TextField(blank=True, help_text='O que fiz, nas minhas palavras.'),
        ),
    ]
