# Generated by Django 5.2.14 on 2026-07-13 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0011_substituicao_taxonomia_dados'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cravingevent',
            name='substituicao_usada',
        ),
        migrations.RemoveField(
            model_name='dailyentry',
            name='substituicoes',
        ),
    ]
