# Generated by Django 5.2.14 on 2026-05-25 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaselineProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_zero', models.DateField(help_text='Data marcada como Dia 1.')),
                ('cigarros_dia_anterior', models.IntegerField(default=0)),
                ('drinks_semana_anterior', models.IntegerField(default=0)),
                ('custo_mensal_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('carta_ancora', models.TextField(blank=True, help_text='Para o eu de daqui a 30 dias, em crise.')),
                ('motivacoes_desire', models.TextField(blank=True)),
                ('motivacoes_ability', models.TextField(blank=True)),
                ('motivacoes_reasons', models.TextField(blank=True)),
                ('motivacoes_need', models.TextField(blank=True)),
                ('commitment_statement', models.TextField(blank=True)),
                ('baseline_peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('baseline_pa', models.CharField(blank=True, help_text='ex: 120/80', max_length=16)),
                ('baseline_hr_repouso', models.IntegerField(blank=True, null=True)),
                ('pennebaker_dia1', models.TextField(blank=True)),
                ('pennebaker_dia2', models.TextField(blank=True)),
                ('pennebaker_dia3', models.TextField(blank=True)),
                ('pennebaker_dia4', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Substitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128)),
                ('categoria', models.CharField(choices=[('oral', 'Oral (chá, água, goma)'), ('movimento', 'Movimento (caminhar, alongar)'), ('social', 'Social (ligar, mensagem)'), ('cognitivo', 'Cognitivo (escrever, ler)'), ('ambiental', 'Ambiental (mudar ambiente)')], max_length=32)),
                ('eficacia_media', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('vezes_usado', models.PositiveIntegerField(default=0)),
                ('notas', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitutions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128)),
                ('contexto', models.TextField(blank=True)),
                ('emocao_precedente', models.CharField(blank=True, max_length=64)),
                ('halt_mais_comum', models.CharField(blank=True, choices=[('H', 'Hungry'), ('A', 'Angry'), ('L', 'Lonely'), ('T', 'Tired')], max_length=8)),
                ('frequencia_semana', models.PositiveSmallIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IfThenPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gatilho_texto', models.CharField(max_length=255)),
                ('acao', models.TextField()),
                ('ativo', models.BooleanField(default=True)),
                ('vezes_acionado', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ifthen_plans', to=settings.AUTH_USER_MODEL)),
                ('trigger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseline.trigger')),
            ],
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveSmallIntegerField()),
                ('nome', models.CharField(max_length=64)),
                ('como_afeta_uso', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['ordem'],
                'unique_together': {('user', 'ordem')},
            },
        ),
    ]
