# Generated by Django 5.2.14 on 2026-05-29 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseline', '0002_remove_trigger_halt_mais_comum_estadointerno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baselineprofile',
            name='baseline_circ_abdominal',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='cm; jejum, pós-banheiro', max_digits=5, null=True),
        ),
    ]
