# Generated by Django 5.2.14 on 2026-07-12 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseline', '0003_baselineprofile_baseline_circ_abdominal'),
    ]

    operations = [
        migrations.AddField(
            model_name='ifthenplan',
            name='detalhes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ifthenplan',
            name='gatilho',
            field=models.CharField(choices=[('frustracao_trabalho', 'Frustração no trabalho'), ('ansiedade_estresse', 'Ansiedade / estresse'), ('tedio_vazio', 'Tédio / vazio'), ('tristeza_solidao', 'Tristeza / solidão'), ('fim_expediente', 'Fim de expediente'), ('bebendo', 'Bebendo (gatilho cruzado)'), ('apos_refeicao', 'Após refeição'), ('cafe_pausa', 'Café / pausa'), ('cansaco_noite_mal_dormida', 'Cansaço / noite mal dormida'), ('dor_mal_estar', 'Dor / mal-estar'), ('comemoracao', 'Comemoração / boa notícia'), ('relaxar_recompensa', 'Relaxar, me recompensar'), ('discussao_atrito', 'Discussão / atrito'), ('evento_social', 'Evento social (bar, churrasco)'), ('alguem_ofereceu', 'Alguém me ofereceu'), ('bom_momento_proximos', 'Bom momento com gente próxima'), ('testar_um_so', 'Testar se consigo parar em um'), ('outro', 'Outro')], default='outro', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ifthenplan',
            name='gatilho_texto',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
