# Generated by Django 5.2.14 on 2026-07-12 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseline', '0005_ifthen_gatilho_dados'),
        ('log', '0009_gatilho_taxonomia_remove'),  # os FKs/M2M para Trigger e EstadoInterno já saíram
    ]

    operations = [
        migrations.RemoveField(
            model_name='trigger',
            name='estado_mais_comum',
        ),
        migrations.RemoveField(
            model_name='trigger',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ifthenplan',
            name='trigger',
        ),
        migrations.RemoveField(
            model_name='ifthenplan',
            name='gatilho_texto',
        ),
        migrations.DeleteModel(
            name='EstadoInterno',
        ),
        migrations.DeleteModel(
            name='Trigger',
        ),
    ]
