# Generated by Django 5.2.14 on 2026-07-13 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("baseline", "0006_apaga_trigger_e_estadointerno"),
        ("log", "0012_substituicao_taxonomia_remove"),  # o FK e o M2M já saíram
    ]

    operations = [
        migrations.DeleteModel(
            name='Substitution',
        ),
    ]
